//
//  RegistrationViewController.swift
//  JoyStickFolio
//
//  Created by Karim Sakr on 14/03/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import FirebaseAnalytics

protocol RegistrationDisplayLogic: AnyObject {
    
    var mainTextField: UITextField { get set }
    
    var secondTextField: UITextField { get set }
    
    var activityIndicator: UIActivityIndicatorView { get set }
    
    var submitButton: UIButton { get set }
    
    var progressBarView: UIProgressView { get set }
    
    var titleLabel: UILabel { get set }
    
    func showError(with message: String)
    
    func dismissRegistrationScreen()
    
}

class RegistrationViewController: UIViewController, RegistrationDisplayLogic {
    
    var interactor: RegistrationBusinessLogic?
  var router: RegistrationRouter?
    
    private let animator = TextAnimator()
    
    private let bag = DisposeBag()
    
    var dismissalCompletion: (() -> Void)?
    
    //MARK: - titleLabel
    lazy var titleLabel: UILabel = {
        let label = UILabel()
        label.numberOfLines = 5
        label.textAlignment = .center
        label.font = UIFont.monospacedDigitSystemFont(ofSize: 30.0, weight: .regular)
        label.translatesAutoresizingMaskIntoConstraints = false
        return label
    }()
    
    //MARK: - TextField
    lazy var mainTextField: UITextField = {
        let field = UITextField()
        field.returnKeyType = .next
        field.leftViewMode = .always
        field.leftView = UIView(frame: CGRect(x: 0, y: 0, width: 10, height: 0))
        field.autocapitalizationType = .none
        field.autocorrectionType = .no
        field.layer.masksToBounds = true
        field.layer.cornerRadius = Constants.cornerRadius
        field.backgroundColor = .secondarySystemBackground
        field.layer.borderWidth = 1.0
        field.layer.borderColor = UIColor.secondaryLabel.cgColor
        field.textContentType = .name
        field.translatesAutoresizingMaskIntoConstraints = false
        return field
    }()
    
    //MARK: - Second TextField
    lazy var secondTextField: UITextField = {
        let field = UITextField()
        field.placeholder = "Password..."
        field.isSecureTextEntry = true
        field.returnKeyType = .next
        field.leftViewMode = .always
        field.leftView = UIView(frame: CGRect(x: 0, y: 0, width: 10, height: 0))
        field.autocapitalizationType = .none
        field.autocorrectionType = .no
        field.layer.masksToBounds = true
        field.layer.cornerRadius = Constants.cornerRadius
        field.backgroundColor = .secondarySystemBackground
        field.layer.borderWidth = 1.0
        field.layer.borderColor = UIColor.secondaryLabel.cgColor
        field.isHidden = true
        field.textContentType = .newPassword
        field.translatesAutoresizingMaskIntoConstraints = false
        return field
    }()
    
    //MARK: - Button
    lazy var submitButton: UIButton = {
        let button = UIButton()
        button.setTitle("Next", for: .normal)
        button.layer.masksToBounds = true
        button.layer.cornerRadius = Constants.cornerRadius
        button.backgroundColor = .accent
        button.setTitleColor(.white, for: .normal)
        button.translatesAutoresizingMaskIntoConstraints = false
        return button
    }()
    
    //MARK: - progressBarView
    lazy var progressBarView: UIProgressView = {
        let progressBar = UIProgressView()
        progressBar.progress = 0.0
        progressBar.progressTintColor = .accent
        progressBar.translatesAutoresizingMaskIntoConstraints = false
        return progressBar
    }()
    
    //MARK: - activityIndicator
    lazy var activityIndicator: UIActivityIndicatorView = {
        let activityIndicator = UIActivityIndicatorView(style: .large)
        activityIndicator.hidesWhenStopped = true
        activityIndicator.translatesAutoresizingMaskIntoConstraints = false
        return activityIndicator
    }()
}

// MARK: View lifecycle
extension RegistrationViewController {
    
    override func viewDidLoad() {
      super.viewDidLoad()
        
        view.backgroundColor = .systemBackground
        setup()
        setupButton()
        setupViewsData()
        addUIViews()
        animateText()
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        // Add constraints for progressBarView
        NSLayoutConstraint.activate([
            
            // Add constraints for progressBarView
            progressBarView.topAnchor.constraint(equalTo: view.topAnchor, constant: 60),
            progressBarView.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            progressBarView.widthAnchor.constraint(equalTo: view.widthAnchor, multiplier: 0.8),
            progressBarView.heightAnchor.constraint(equalToConstant: 10),
            
            titleLabel.topAnchor.constraint(equalTo: progressBarView.bottomAnchor, constant: 40),
            titleLabel.widthAnchor.constraint(equalToConstant: 330),
            titleLabel.heightAnchor.constraint(equalToConstant: 150),
            titleLabel.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            
            // Add constraints for textField
            mainTextField.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            mainTextField.topAnchor.constraint(equalTo: titleLabel.bottomAnchor, constant: 70),
            mainTextField.widthAnchor.constraint(equalToConstant: 340),
            mainTextField.heightAnchor.constraint(equalToConstant: 52),

            // Add constraints for secondTextField
            secondTextField.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 25),
            secondTextField.bottomAnchor.constraint(equalTo: mainTextField.topAnchor, constant: -10),
            secondTextField.widthAnchor.constraint(equalToConstant: 340),
            secondTextField.heightAnchor.constraint(equalToConstant: 52),
            
            // Add constraints for submitButton
            submitButton.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 25),
            submitButton.topAnchor.constraint(equalTo: mainTextField.bottomAnchor, constant: 10),
            submitButton.widthAnchor.constraint(equalToConstant: 340),
            submitButton.heightAnchor.constraint(equalToConstant: 52),
            
            // Add constraints for activityIndicator
            activityIndicator.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            activityIndicator.centerYAnchor.constraint(equalTo: view.centerYAnchor),
        ])
    }
}

//MARK: - setup
extension RegistrationViewController {
    
    private func setup() {
        let viewController = self
        let interactor = RegistrationInteractor()
        let presenter = RegistrationPresenter()
        let router = RegistrationRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    

    func setupButton() {
        submitButton.addTarget(self, action: #selector(buttonPressed), for: .touchUpInside)
    }
    
    func setupViewsData() {
        guard let interactor = interactor else { return }
        mainTextField.placeholder = interactor.processes[interactor.index].placeholder
        submitButton.setTitle(interactor.processes[interactor.index].buttonTitle, for: .normal)
        titleLabel.text = interactor.processes[interactor.index].title
        progressBarView.progress = Float(interactor.progressValue)
    }
    
    func addUIViews() {
        view.addSubview(progressBarView)
        view.addSubview(mainTextField)
        view.addSubview(secondTextField)
        view.addSubview(submitButton)
        view.addSubview(titleLabel)
        view.addSubview(activityIndicator)
    }
    
    func animateText() {
        guard let interactor = interactor else { return }
        titleLabel.text? = ""
        self.animator.animateTitle(text: self.interactor!.processes[interactor.index].title, timeInterval: 0.01) { letter in
            self.titleLabel.text?.append(letter)
        }
    }
}

//MARK: - functions
extension RegistrationViewController {
    
    @objc private func buttonPressed() {
        
        var isSuccessful: Bool = false
        
        guard let interactor = interactor else { return }
        Task {

            if interactor.processes.last != interactor.processes[interactor.index] {

                switch interactor.processes[interactor.index].process {

                case .enterFullName:
                    isSuccessful = interactor.didEnterFullNameSuccessfully(fullName: mainTextField.text ?? "")

                case .enterEmail:
                    isSuccessful = interactor.didEnterEmailSuccessfully(email: mainTextField.text ?? "")

                case .enterUsername:
                    isModalInPresentation = true
                    isSuccessful = await interactor.didEnterUsernameSuccessfully(username: mainTextField.text ?? "")
                    isModalInPresentation = false
                    
                case .enterPassword:
                    isModalInPresentation = true
                    isSuccessful = await interactor.didEnterPasswordSuccessfully(password: mainTextField.text ?? "", repeatPassword: secondTextField.text ?? "")
                    isModalInPresentation = false
                    
                case .loading:
                    break
                }
                if isSuccessful{
                    interactor.nextEntry()
                }
            }
        }
    }
    
    func dismissRegistrationScreen(){
        dismiss(animated: false) {
            self.dismissalCompletion?()
        }
    }
    
    func addLoadingIndicator() {
        isModalInPresentation = true
        activityIndicator.isHidden = false
        activityIndicator.startAnimating()
    }
    
    func removeLoadingIndicator() {
        isModalInPresentation = false
        activityIndicator.stopAnimating()
        activityIndicator.isHidden = true
    }
    
    func showError(with message: String) {
        DispatchQueue.main.async {
            AppSnackBar.make(in: self.view, message: message, duration: .lengthLong).show()
        }
    }
}

//MARK: - UITextFieldDelegate
extension RegistrationViewController: UITextFieldDelegate {
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        
        if textField == mainTextField {
            buttonPressed()
        } else if textField == secondTextField {
            self.mainTextField.becomeFirstResponder()
        }
        
        return true
    }
}
