//
//  HamburgerMenuModels.swift
//  JoyStickFolio
//
//  Created by Karim Sakr on 17/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct HamburgerMenuModels {
    
    // requests here
    struct Request {
        struct HamburgerMenuCell {
            let title: String
            let handler: (() -> Void)
        }

    }
    
    struct ViewModels {
        
        // response here
        
    }
    
}
