//
//  RegistrationInteractor.swift
//  JoyStickFolio
//
//  Created by Karim Sakr on 14/03/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol RegistrationBusinessLogic {
    
    var data: [String : String] { get set}
    
    func isUsernameAvailble(username: String) async -> Bool
    
    func registerUser() async -> Observable<Void>
    
    func fullNameEntered(fullName: String)
    
    func emailEntered(email: String)
    
    func usernameEntered(username: String)
    
    func passwordEntered(password: String)
    
    func isFullNameValid(textField: String) -> Bool
    
    func isEmailValid(textField: String) -> Bool
    
    func isUsernameValid(textField: String) -> Bool
    
    func isPasswordValid(textfield: String, repeatTextField: String) -> Bool
  
}

protocol RegistrationDataStore {
    
}

class RegistrationInteractor: RegistrationBusinessLogic, RegistrationDataStore {
  var presenter: RegistrationPresentationLogic?

    //MARK: - Managers
    private let authenticationManager = AuthenticationManager()
    private let databaseManager = DatabaseManager()
    
    //MARK: - Auth Validator
    private let validator = AuthValidator()
    
    //MARK: - User Data
    var data: [String : String] = [:]
    
    func isUsernameAvailble(username: String) async -> Bool {
        return await databaseManager.isUsernameAvailable(username: username)
    }
    
    //MARK: - registerUser
    func registerUser() async -> Observable<Void> {
        return await authenticationManager.createUser(with: data)
    }
    
    //MARK: - fullNameEntered
    func fullNameEntered(fullName: String) {
        data[Constants.Key.Auth.fullName] = fullName
    }
    
    //MARK: - emailEntered
    func emailEntered(email: String) {
        data[Constants.Key.Auth.email] = email
    }
    
    //MARK: - usernameEntered
    func usernameEntered(username: String) {
        data[Constants.Key.Auth.username] = username
    }
    
    //MARK: - passwordEnetred
    func passwordEntered(password: String) {
        data[Constants.Key.Auth.password] = password
    }
    
    //MARK: - Validators
    func isFullNameValid(textField: String) -> Bool {
        return validator.isFullNameValid(textField: textField)
    }
    
    func isEmailValid(textField: String) -> Bool {
        return validator.isEmailValid(textField: textField)
    }
    
    func isUsernameValid(textField: String) -> Bool {
        return validator.isUsernameValid(textField: textField)
    }
    
    func isPasswordValid(textfield: String, repeatTextField: String) -> Bool {
        return validator.isPasswordValid(textfield: textfield, repeatTextField: repeatTextField)
    }
}
