//
//  RegistrationModels.swift
//  JoyStickFolio
//
//  Created by Karim Sakr on 14/03/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct RegistrationModels {
    
    // requests here
    struct Request {
        
        struct RegistrationProcess: Equatable {
            let title      : String
            let placeholder: String
            let buttonTitle: String
            let process    : Process
        }
        
        struct CreatedUserProfile: Encodable {
            let email   : String
            let fullName: String
            let username: String
        }


        
    }
    
    struct ViewModels {
        
        // response here
        
    }
    
}
