//
//  LoginRouter.swift
//  JoyStickFolio
//
//  Created by Karim Sakr on 11/03/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    
    func goToCreateAccount(completion: (() -> Void)?)
    
    func dismissLoginScreen()
    
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    func goToCreateAccount(completion: (() -> Void)? = nil) {
        guard let viewController = viewController else { return }
        let vc = RegistrationViewController()
        vc.title = "Create Account"
        vc.dismissalCompletion = {
            completion?()
        }
        viewController.present(UINavigationController(rootViewController: vc), animated: true)
    }
    
    func dismissLoginScreen() {
        guard let viewController = viewController else { return }
        viewController.dismissLoginScreen()
    }
    
}
