//
//  LoginPresenter.swift
//  JoyStickFolio
//
//  Created by Karim Sakr on 11/03/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func stopLoading()
    func dismissLoginScreen()
    func showSnackbar(with message: String)
}

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?
    
    
    func stopLoading(){
        guard let viewController = viewController else { return }
        viewController.stopLoading()
    }
    
    func dismissLoginScreen() {
        guard let viewController = viewController else { return }
        viewController.dismissLoginScreen()
    }
    
    func showSnackbar(with message: String) {
        viewController?.showSnackbar(with: message)
    }
    
}
